openapi: 3.0.3

info:
  title: Hello Service
  description: The Hello Service provides some functionality.
  version: 1.0.0

servers:
  - url: http://localhost:8080/v1
  - url: https://hello.<no value>/v1

paths:
  /hello/{name}:
    get:
      operationId: getHelloName
      summary: Get Hello Name
      description: GetHelloName says hello to the inputted name.
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
            description: Name is the person we're saying hello to.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hello'
        500:
          description: Internal Server Error

components:
  schemas:
    Hello:
      type: object
      description: An object description.
      required:
        - id
        - message
      properties:
        id:
          type: string
          description: ID is a unique identifier for the Hello.
          format: uuid
          x-go-name: ID
          x-go-type: string
        message:
          type: string
          description: Message is a hello note.
          x-oapi-codegen-extra-tags:
            tag: "customtagval"
